app:
 name: runtime
 image:
  repository: "onecx/onecx-ai-provider-runtime"
 operator:
  keycloak:
    client:
     enabled: true
  microservice:
   spec:
    description: OneCX AI Provider Runtime
    name: OneCX AI Provider Runtime