# AUTHENTICATION
quarkus.http.auth.permission.health.paths=/q/*
quarkus.http.auth.permission.health.policy=permit
quarkus.http.auth.permission.default.paths=/*
quarkus.http.auth.permission.default.policy=authenticated
onecx.permissions.application-id=${quarkus.application.name}
quarkus.fault-tolerance."org.tkit.onecx.ai.provider.runtime.services.mcp.McpService/receiveToolSpecifications".retry.max-retries=${onecx.ai.dispatch.mcp.max-tool-execution-retries:3}
quarkus.fault-tolerance."org.tkit.onecx.ai.provider.runtime.services.mcp.McpService/receiveToolSpecifications".retry.delay=${onecx.ai.dispatch.mcp.tool-execution-retry-delay:1000}
quarkus.langchain4j.chat-model.provider=ollama

# PROD

# DEV

# OIDC
%prod.quarkus.oidc-client.client-id=${quarkus.application.name}
# INTEGRATION TEST
quarkus.test.integration-test-profile=test
# TEST
%test.quarkus.http.test-port=0
%test.tkit.log.json.enabled=false
%test.quarkus.mockserver.devservices.config-class-path=true
%test.quarkus.mockserver.devservices.config-file=/mockserver.properties
%test.quarkus.mockserver.devservices.config-dir=/mockserver
%test.quarkus.mockserver.devservices.log=false
%test.quarkus.mockserver.devservices.reuse=true

%test.quarkus.rest-client.onecx_permission.url=${quarkus.mockserver.endpoint}
%test.quarkus.keycloak.devservices.roles.alice=role-admin
%test.quarkus.keycloak.devservices.roles.bob=role-user
%test.quarkus.oidc-client.auth-server-url=${quarkus.oidc.auth-server-url}
%test.quarkus.oidc-client.client-id=${quarkus.oidc.client-id}
%test.quarkus.oidc-client.credentials.secret=${quarkus.oidc.credentials.secret}
%test.onecx.permissions.product-name=applications
# PIPE CONFIG


